first-time: true
url: "http://localhost:8080"
secrets:
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "yourmail@mail.com"
    password: "XXXX XXXX XXXX XXXX"
    properties:
      mail:
        transport:
          protocol: "smtp"
        smtp:
          auth: "true"
          starttls:
            enable: "true"
      debug: "false"
settings:
  storageType: "DATABASE"
  mail:
    own: true